name: Convert RST to HTML

on:
  push:
    paths:
      - '**.rst'
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert all RST files to HTML if needed
        run: |
          shopt -s nullglob
          for rst in *.rst; do
            html="${rst%.rst}.html"
            if [ ! -f "$html" ] || [ "$rst" -nt "$html" ]; then
              echo "Converting $rst to $html..."
              pandoc "$rst" -f rst -t html -o "$html"
            else
              echo "$html is up-to-date. Skipping."
            fi
          done
