name: Convert RST to HTML

on:
  push:
    paths:
      - '**.rst'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert RST files to HTML
        run: |
          shopt -s nullglob
          for rst in **/*.rst; do
            html="${rst%.rst}.html"
            if [ ! -f "$html" ] || [ "$rst" -nt "$html" ]; then
              echo "Converting $rst to $html..."
              pandoc "$rst" --from=rst --to=html -o "$html" --standalone
            else
              echo "Skipping $rst — up-to-date."
            fi
          done

      - name: Commit and push generated HTML files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add **/*.html

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate HTML from RST via GitHub Actions"
            git push
          fi

          else
            git commit -m "Auto-generate HTML from RST via GitHub Actions"
            git push
          fi
