# .github/workflows/rst-to-html.yml
name: Convert RST to HTML

on:
  push:
    paths:
      - '**.rst'
  pull_request:
    paths:
      - '**.rst'

jobs:
  convert-rst-to-html:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docutils
        
    - name: Get changed RST files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **.rst
          
    - name: Debug changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Changed files detected:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        echo "Any changed: ${{ steps.changed-files.outputs.any_changed }}"
        
    - name: Convert RST files to HTML
      run: |
        # Create conversion script
        cat > convert_rst.py << 'EOF'
        import os
        import sys
        from docutils.core import publish_file
        
        def convert_rst_to_html(rst_file):
            # Determine output HTML file path
            html_file = os.path.splitext(rst_file)[0] + '.html'
            
            try:
                # Convert RST to HTML using docutils
                publish_file(
                    source_path=rst_file,
                    destination_path=html_file,
                    writer_name='html',
                    settings_overrides={
                        'input_encoding': 'utf-8',
                        'output_encoding': 'utf-8',
                        'embed_stylesheet': False,
                        'raw_enabled': True,
                        'file_insertion_enabled': False,
                        'halt_level': 2,
                        'report_level': 2,
                        'doctitle_xform': False,
                        'initial_header_level': 1,
                    }
                )
                print(f"✓ Converted {rst_file} to {html_file}")
                return html_file
                
            except Exception as e:
                print(f"✗ Error converting {rst_file}: {e}")
                # Try with more permissive settings
                try:
                    publish_file(
                        source_path=rst_file,
                        destination_path=html_file,
                        writer_name='html',
                        settings_overrides={
                            'input_encoding': 'utf-8',
                            'output_encoding': 'utf-8',
                            'embed_stylesheet': False,
                            'raw_enabled': True,
                            'file_insertion_enabled': False,
                            'halt_level': 5,  # More permissive
                            'report_level': 5,
                        }
                    )
                    print(f"✓ Converted {rst_file} to {html_file} (permissive mode)")
                    return html_file
                except Exception as e2:
                    print(f"✗ Failed to convert {rst_file}: {e2}")
                    raise e2
        
        if __name__ == "__main__":
            import sys
            print(f"Arguments received: {sys.argv}")
            
            # Get changed files from command line arguments
            if len(sys.argv) > 1:
                changed_files = sys.argv[1].split()  # Split space-separated files
            else:
                print("No files provided as arguments")
                sys.exit(0)
            
            print(f"Processing files: {changed_files}")
            converted_files = []
            
            for rst_file in changed_files:
                rst_file = rst_file.strip()  # Remove any whitespace
                print(f"Checking file: '{rst_file}'")
                
                if rst_file.endswith('.rst'):
                    if os.path.exists(rst_file):
                        print(f"Converting {rst_file}...")
                        try:
                            html_file = convert_rst_to_html(rst_file)
                            converted_files.append(html_file)
                        except Exception as e:
                            print(f"✗ Error converting {rst_file}: {e}")
                            sys.exit(1)
                    else:
                        print(f"File does not exist: {rst_file}")
                else:
                    print(f"Skipping non-RST file: {rst_file}")
            
            # Output list of converted files for next step
            if converted_files:
                print(f"Converted files: {converted_files}")
                with open('converted_files.txt', 'w') as f:
                    f.write('\n'.join(converted_files))
                print("Conversion completed successfully")
            else:
                print("No files were converted")
        EOF
        
        # Check what files we're working with
        echo "All changed files from GitHub Actions:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        
        # Run conversion on changed files
        if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
          echo "Running conversion script on changed files..."
          python convert_rst.py "${{ steps.changed-files.outputs.all_changed_files }}"
        else
          echo "No changed files detected, checking for any RST files..."
          # Find all RST files in the repository as fallback
          rst_files=$(find . -name "*.rst" -type f | head -10)  # Limit to first 10 files
          if [ -n "$rst_files" ]; then
            echo "Found RST files: $rst_files"
            python convert_rst.py "$rst_files"
          else
            echo "No RST files found in repository"
          fi
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add converted HTML files
        if [ -f "converted_files.txt" ]; then
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              git add "$file"
              echo "Added $file to git"
            fi
          done < converted_files.txt
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update HTML files from RST changes
            
            Updated files:
            $(cat converted_files.txt | sed 's/^/- /')"
            
            git push
          fi
        fi
