name: Convert RST to HTML

on:
  push:
    paths:
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Delete old HTML if it exists
        run: |
          FILE="document.rst"
          OUTPUT="${FILE%.rst}.html"
          if [ -f "$OUTPUT" ]; then
            rm "$OUTPUT"
            echo "Deleted old $OUTPUT"
          fi

      - name: Convert RST to HTML
        run: |
          FILE="test1.rst"
          OUTPUT="${FILE%.rst}.html"
          pandoc "$FILE" -f rst -t html -o "$OUTPUT"
